/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FrontEnd;

import BackEnd.ConexaoMySQL;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Igor
 */
public class CaCadastrarProprietario extends javax.swing.JDialog {
    
    private ConexaoMySQL c;
    private int Cod;

    /**
     * Creates new form CaCadastrarProprietario
     */
    public CaCadastrarProprietario(int Codigo) {
        initComponents();
        this.c = new ConexaoMySQL();
        this.setModal(true);
         Cod= Codigo;
        
         
         if(Codigo == 0){
            this.setTitle("Cadastrando Proprietario");

        }
        else{
            this.setTitle("Editando Proprietario");

            try{
                String SQL="select * From proprietario where codProprietario = "+Codigo;
                this.c.setResultSet(SQL);
                this.c.getResultSet().next();

                txtNome.setText(this.c.getResultSet().getString("Nome"));
                txtCPF.setText(this.c.getResultSet().getString("CPF"));
                txtEndereco.setText(this.c.getResultSet().getString("Endereco"));
                txtContato.setText(this.c.getResultSet().getString("Contatos"));

            }
            catch(SQLException e){
                JOptionPane.showMessageDialog(this, "Teste "+e);
            }
        }
        
    }
        public boolean IsInt(JTextField TextField, String Campo){
        try {
            int i=Integer.parseInt(TextField.getText());
            return true;
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(
                    null,
                    "O valor do campo '" + Campo + "' não é válido. \n Informe um valor Inteiro.",
                    "Erro de Entrada" , JOptionPane.ERROR_MESSAGE);
            TextField.requestFocus();
            TextField.setText("");
            return false;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtEndereco = new javax.swing.JTextField();
        btnSalvar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        lblNome = new javax.swing.JLabel();
        lblCPF = new javax.swing.JLabel();
        lblEndereco = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        txtCPF = new javax.swing.JTextField();
        lblContato = new javax.swing.JLabel();
        txtContato = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        lblNome.setText("Nome :");

        lblCPF.setText("CPF :");

        lblEndereco.setText("Endereco :");

        lblContato.setText("Contato :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblEndereco)
                                .addComponent(lblCPF)
                                .addComponent(lblNome))
                            .addGap(280, 280, 280))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtNome, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 324, Short.MAX_VALUE)
                            .addComponent(txtCPF, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtEndereco, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtContato, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addComponent(lblContato)))
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblNome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCPF)
                .addGap(3, 3, 3)
                .addComponent(txtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblEndereco)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblContato)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtContato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed

        if(IsInt(txtCPF, "CPF" )&& IsInt(txtContato, "Contato" )){
            
            // Toda essa sequencia de Strings seguido de Ifs é para verificar se os campos foram preenchidos 
            
            String CPF=txtCPF.getText();
            int TamanhoCPF=CPF.length();
            String Nome=txtNome.getText();
            int TamanhoNome=Nome.length();
            String Endereco=txtEndereco.getText();
            int TamanhoEndereco=Endereco.length();
            String Contato=txtContato.getText();
            int TamanhoContato=Contato.length();
            
            if(TamanhoCPF>=6){
                if(TamanhoContato>=1){
                    if(TamanhoNome>=1){
                        if(TamanhoEndereco>=1){
                            
                            if(Cod==0){
                            String SQL="Insert into proprietario(Nome, CPF, Endereco, Contatos)"
                                + " Values('" + txtNome.getText() + "','" +txtCPF.getText() + "','" +txtEndereco.getText() +"','"+txtContato.getText()+"');";
                            this.c.SQLExecute(SQL);
                            this.dispose();
                            JOptionPane.showMessageDialog(this, "Cadastrado com sucesso");
                            }
                            else{
                                String SQL= "Update proprietario set Nome = '"+txtNome.getText()+"',CPF = '"+txtCPF.getText()+"'"
                                + ",Endereco = '"+txtEndereco.getText()+"',Contatos = '"+txtContato.getText()+"' where( CodProprietario = '"+Cod+"' )";
                        this.c.SQLExecute(SQL);
                        this.dispose();
                        JOptionPane.showMessageDialog(this, "Editado com sucesso"); 
                            }



                        }
                        else{
                            JOptionPane.showMessageDialog(this, "O Endereco está muito pequeno");
                            txtEndereco.setText("");
                             txtEndereco.requestFocus();
                        }  
                    }
                    else{
                        JOptionPane.showMessageDialog(this, "O Nome está muito pequeno");
                     }
                    txtNome.setText("");
                    txtNome.requestFocus();
                }
                else{
                    JOptionPane.showMessageDialog(this, "O campo Contato está muito pequeno");
                    txtContato.setText("");
                    txtContato.requestFocus();
            }
            }
            else{
                JOptionPane.showMessageDialog(this, "O CPF está muito pequeno");
                txtCPF.setText("");
                txtCPF.requestFocus();
            }
            
            
            
            
        }
        
        
        
        
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JLabel lblCPF;
    private javax.swing.JLabel lblContato;
    private javax.swing.JLabel lblEndereco;
    private javax.swing.JLabel lblNome;
    private javax.swing.JTextField txtCPF;
    private javax.swing.JTextField txtContato;
    private javax.swing.JTextField txtEndereco;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables
}
